name: Claude Issue Assistant

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  claude-assist:
    if: |
      (github.event_name == 'issues' && 
       (github.event.action == 'opened' || 
        contains(github.event.label.name, 'claude'))) ||
      (github.event_name == 'issue_comment' && 
       !github.event.issue.pull_request &&
       contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: Run Claude Assistant
        uses: anthropics/claude-code-action@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-5-sonnet-20241022
          system-prompt: |
            You are a helpful AI assistant for this repository.
            Help users with their questions, provide code examples,
            and suggest solutions to their problems.
            Be friendly, professional, and thorough in your responses.